### ISSUE TITLE
Discrepancy in Reproducing TSP1000

### ISSUE THREAD

**Issue by xyfffff** [yimengmin/UTSP#1]
Hello, Yimeng

I'm currently working on reproducing the experimental results and have encountered some discrepancies that I would like to address.

Following the instructions on your Github repository, I downloaded the input file that was  hosted on Google Drive. I then ran the MCTS with the same parameters specified in the original paper. For a TSP instance with 1000 nodes, I used the command:
`./new-solve-200.sh 0 5 100 0 50 2 1 1
`
Additionally, I made sure to update the node size variable in both `TSP_IO.h` and `new-solve-200.sh` scripts from 200 to 1000 to match the problem scale.

However, I am observing some differences in the results when compared to those presented in Table 2 of the paper. My MCTS is taking longer to run, clocking in at **5.87** minutes instead of the reported **2.67** minutes. Moreover, the gap in solution quality has increased; whereas the paper reports a gap of **1.177%**, the gap in my results is **1.359%**.

Could you please help me understand the possible reasons for this discrepancy? Is there any chance that there are additional search parameters that I might need to adjust, or could there be other factors at play here?

Thank you for your assistance in resolving this issue. I am looking forward to any insights or suggestions you might have.

Best regards,
Yifan

**Comment by yimengmin** [comment]
Hello Yifan

go to `Search/code/include/TSP_IO.h ` and set the `double Param_T=0.04;`

on TSP-1000 I am using `./new-solve-1000.sh 0 5 10 0 150 3 1 1`
 
You should train the model and fine-tune on the local. Additionally, here's a different TSP-1000 input file for you to attempt: 

https://drive.google.com/file/d/1w8QKtpVKZiJhQV2n1wrpvBwLZtUShj7T/view?usp=drive_link

different CPU can also cause the discrepancy, my setup is running on an Intel Xeon Gold 6326.

**Comment by xyfffff** [comment]
Hello Yimeng,

Thank you for your additional guidance. I have conducted further experiments and here’s what I found:

1. Setting `double Param_T=0.04` in `TSP_IO.h` and running `./new-solve-1000.sh 0 5 10 0 150 3 1 1`, the results were `3.28` minutes with a gap of `1.762%`. Subsequently, setting `Param_T` to `0.08` resulted in a runtime of `5.92` minutes and a gap of `1.35%`, while setting `Param_T` to `0.16` resulted in a runtime of `11.28` minutes and a gap of `1.153%`, matching the `1.177%` reported in Table 2. These observations lead me to concur with your assessment that the discrepancies could indeed be due to differences in our CPUs; the longer runtimes might be contributing to achieving the expected results.
2. Regarding the training or fine-tuning of the model, I would like to clarify if it is necessary for me to retrain the model, given that the input file from Google Drive is the heat map generated by the already trained model. Could you confirm if the input file you’ve provided is predicted by a model that has already been fine-tuned, or should I proceed with a fresh training cycle?
3. Additionally, I have a question regarding the training parameters for TSP1000. In your GitHub repository, the training parameters specified for TSP200 are as follows:
`python train.py --num_of_nodes 200 --EPOCHS 300 --batch_size 32 --temperature 3.5 --C1_penalty 20.0 --nlayers 2 --hidden 64 --rescale 2.0 --moment 1 --lr 5e-3 --stepsize 20
`
When adapting these settings for TSP1000, should all parameters remain constant except for `--num_of_nodes` and `--EPOCHS`? Or would you recommend adjusting other parameters as well to better suit the increased problem size?
5. Lastly, I appreciate your providing a new TSP-1000 input file link. However, it appears to require access permission, which I have already requested. Additionally, could you explain if there are any significant differences between this new TSP-1000 input file and the original one provided?

Best regards,
Yifan

**Comment by yimengmin** [comment]
Sorry, I just give you access, try the new TSP-1000 input file,

If you want to train TSP-1000, you cantune all these following parameters:
`--temperature 3.5 --C1_penalty 20.0 --nlayers 2 --hidden 64 --rescale 2.0 --moment 1 --lr 5e-3 --stepsize 20`

the TSP-1000 training data is here:
 https://drive.google.com/drive/folders/1Nyo-npHoY_JuXu4ER-tATeR-cceoDaL7?usp=sharing

I will update the readme file later

**Comment by xyfffff** [comment]
Got it, thanks!
