### ISSUE TITLE
Request for model checkpoints

### ISSUE THREAD

**Issue by xyfffff** [yimengmin/UTSP#2]
Hello Yimeng,

I am currently attempting to reproduce your model, and having access to the pre-trained checkpoints would be very beneficial, since I am concerned that re-training the model myself might introduce discrepancies due to potential differences in parameter settings or other subtle implementation details.

Your assistance would greatly aid in ensuring the reproducibility of your work, which is a cornerstone of scientific research! Thank you for considering my request!

Best regards,
Yifan

**Comment by yimengmin** [comment]
Hi yifan
I will update this repo later this year, (after NeruIPS conference).
Here I include the checkpoints for TSP-1000, include the Search File (use T=0.04), hope this is helpful:

https://drive.google.com/drive/folders/18-VZmUg63bwWN981M_jdLR12vVfn47O1?usp=sharing

I am running
`
python loadmodel.py --num_of_nodes 1000  --batch_size 64 --temperature 3.5  --nlayers 2 --hidden 128 --rescale 4.
`
in loadmodel.py
we set: `Saved_indices,Saved_Values,Saved_sol,Saved_pos = test(test_loader,topk = 10)`

you can train the model and try other hyper-parameters, I didn't find tune these hyper-parameters, so you should be able to find better heat map if you fine tune the model.

Regard the I/O Time:

On TSP-1000, the I/O can be time consuming.

In fact, for fair comparison with Att-GCN+MCTS, the process in the `loadmodel` section and the subsequent search involve storing and retrieving a sparse heat map in an N by N format. This approach results in increased I/O time. However, if the heat map is saved and loaded in a more compact, sparse manner, it would significantly cut down the time required. This improvement should be reflected in a reduced overall time reported in the UTSP paper.
