### ISSUE TITLE
Input data file

### ISSUE THREAD

**Issue by EchizenG** [yimengmin/UTSP#3]
Hi Yimeng,

I am trying to train the model under 'num_of_nodes=20' but there is no file such as 'train_tsp_instance_20.npy' in ./data folder. I downloaded the 'instances.zip' from the link you provided. However, simply rename is to '.npy' file doesn't work.

**Comment by yimengmin** [comment]
check this: https://drive.google.com/drive/folders/18Exv_Oah8SZe_vLC7X4ccmP3TOcs-0E3?usp=sharing
the smallinstances.zip

**Comment by EchizenG** [comment]
Thank you for your reply. It doesn't work either. Here is the reported message:

` python train.py --num_of_nodes 20 --EPOCHS 300 --batch_size 32 --temperature 3.5  --C1_penalty 20.0 --nlayers 2 --hidden 64 --rescale 2.0 --mont 1 --lr 5e-3 --stepsize 20
Traceback (most recent call last):
  File "train.py", line 55, in <module>
    tsp_instances = np.load('./data/train_tsp_instance_%d.npy'%args.num_of_nodes)
  File "/home/yang/anaconda3/envs/tsp/lib/python3.8/site-packages/numpy/lib/npyio.py", line 438, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
`

**Comment by EchizenG** [comment]
It works! Thank you so much!
