### ISSUE TITLE
The intuition behind using an additional soft indicator matrix

### ISSUE THREAD

**Issue by bokveizen** [yimengmin/UTSP#5]
Dear Yimeng,

Thank you for your wonderful work.
I have a question: what is your intuition behind using an additional soft indicator matrix (instead of directly outputting a heatmap using the GNN)?

As I can see, it is also possible to directly generate $\mathcal{H}$.

Thank you for your help in advance!

Best,
Fanchen

**Comment by yimengmin** [comment]
directly generate $H$ does not encode the Hamiltonian cycle constraint, an example is shown in Figure 1 in the NeurIPS paper.
