### ISSUE TITLE
Problems in reproducing the TSP500.

### ISSUE THREAD

**Issue by asimfish** [yimengmin/UTSP#6]
Hello, Yimeng

I have some trouble in reproducing the TSP500.

I used the command  from Readme to reproduce the results of tsp500：

python loadmodel.py --num_of_nodes 500 --batch_size 128 --temperature 3.5 --nlayers 2 --hidden 64 --rescale 4.0 --moment 1

./new-solve-500.sh 0 5 100 0 50 2 1 1

and change Param_T = 0.04; Max_Inst_Num = 128; Max_City_Num 500; Rec_Num = 100
and i just used the model and code downloaded from your repository with no other change,But I find the search result very strange, most of the search return 0.0000, only a small part of them are normal:
 
![20240428-134543](https://github.com/yimengmin/UTSP/assets/150761986/8e29c5c5-103f-4b5e-bc50-9fc999a9fe93)

**Comment by yimengmin** [comment]
"Rec_Num = 100" should be Rec_Num = 20

**Comment by asimfish** [comment]
> "Rec_Num = 100" should be Rec_Num = 20

Thanks for your reminding, I changed Rec_Num to 20 and the operation succeeded.
